// SLDS 2 palette — full 173 tokens.
// Source: ~/Downloads/slds-2-colors.html
// Token prefix: --slds-g-color-*

export const sldsColors = [
  { group: 'Surface', token: '--slds-g-color-surface-1', hex: '#ffffff' },
  { group: 'Surface', token: '--slds-g-color-on-surface-1', hex: '#5c5c5c' },
  { group: 'Surface', token: '--slds-g-color-on-surface-2', hex: '#2e2e2e' },
  { group: 'Surface', token: '--slds-g-color-border-2', hex: '#5c5c5c' },
  { group: 'Brand', token: '--slds-g-color-brand-base-10', hex: '#001642' },
  { group: 'Brand', token: '--slds-g-color-brand-base-15', hex: '#001e5b' },
  { group: 'Brand', token: '--slds-g-color-brand-base-20', hex: '#002775' },
  { group: 'Brand', token: '--slds-g-color-brand-base-30', hex: '#022ac0' },
  { group: 'Brand', token: '--slds-g-color-brand-base-40', hex: '#0250d9' },
  { group: 'Brand', token: '--slds-g-color-brand-base-50', hex: '#066afe' },
  { group: 'Brand', token: '--slds-g-color-brand-base-60', hex: '#4992fe' },
  { group: 'Brand', token: '--slds-g-color-brand-base-65', hex: '#5f9ffe' },
  { group: 'Brand', token: '--slds-g-color-brand-base-70', hex: '#7cb1fe' },
  { group: 'Brand', token: '--slds-g-color-brand-base-80', hex: '#a8cbff' },
  { group: 'Brand', token: '--slds-g-color-brand-base-90', hex: '#d6e6ff' },
  { group: 'Brand', token: '--slds-g-color-brand-base-95', hex: '#edf4ff' },
  { group: 'Info', token: '--slds-g-color-info-base-10', hex: '#001639' },
  { group: 'Info', token: '--slds-g-color-info-base-15', hex: '#03234d' },
  { group: 'Info', token: '--slds-g-color-info-base-20', hex: '#032d60' },
  { group: 'Info', token: '--slds-g-color-info-base-30', hex: '#014486' },
  { group: 'Info', token: '--slds-g-color-info-base-40', hex: '#0b5cab' },
  { group: 'Info', token: '--slds-g-color-info-base-50', hex: '#0176d3' },
  { group: 'Info', token: '--slds-g-color-info-base-60', hex: '#1b96ff' },
  { group: 'Info', token: '--slds-g-color-info-base-65', hex: '#57a3fd' },
  { group: 'Info', token: '--slds-g-color-info-base-70', hex: '#78b0fd' },
  { group: 'Info', token: '--slds-g-color-info-base-80', hex: '#aacbff' },
  { group: 'Info', token: '--slds-g-color-info-base-90', hex: '#d8e6fe' },
  { group: 'Info', token: '--slds-g-color-info-base-95', hex: '#eef4ff' },
  { group: 'Success', token: '--slds-g-color-success-base-10', hex: '#071b12' },
  { group: 'Success', token: '--slds-g-color-success-base-15', hex: '#072825' },
  { group: 'Success', token: '--slds-g-color-success-base-20', hex: '#023434' },
  { group: 'Success', token: '--slds-g-color-success-base-30', hex: '#024d4c' },
  { group: 'Success', token: '--slds-g-color-success-base-40', hex: '#056764' },
  { group: 'Success', token: '--slds-g-color-success-base-50', hex: '#0b827c' },
  { group: 'Success', token: '--slds-g-color-success-base-60', hex: '#06a59a' },
  { group: 'Success', token: '--slds-g-color-success-base-65', hex: '#03b4a7' },
  { group: 'Success', token: '--slds-g-color-success-base-70', hex: '#01c3b3' },
  { group: 'Success', token: '--slds-g-color-success-base-80', hex: '#04e1cb' },
  { group: 'Success', token: '--slds-g-color-success-base-90', hex: '#acf3e4' },
  { group: 'Success', token: '--slds-g-color-success-base-95', hex: '#def9f3' },
  { group: 'Warning', token: '--slds-g-color-warning-base-10', hex: '#281202' },
  { group: 'Warning', token: '--slds-g-color-warning-base-15', hex: '#371e03' },
  { group: 'Warning', token: '--slds-g-color-warning-base-20', hex: '#4f2100' },
  { group: 'Warning', token: '--slds-g-color-warning-base-30', hex: '#6f3400' },
  { group: 'Warning', token: '--slds-g-color-warning-base-40', hex: '#8c4b02' },
  { group: 'Warning', token: '--slds-g-color-warning-base-50', hex: '#a96504' },
  { group: 'Warning', token: '--slds-g-color-warning-base-60', hex: '#ca8501' },
  { group: 'Warning', token: '--slds-g-color-warning-base-65', hex: '#da9401' },
  { group: 'Warning', token: '--slds-g-color-warning-base-70', hex: '#e4a201' },
  { group: 'Warning', token: '--slds-g-color-warning-base-80', hex: '#fcc003' },
  { group: 'Warning', token: '--slds-g-color-warning-base-90', hex: '#f9e3b6' },
  { group: 'Warning', token: '--slds-g-color-warning-base-95', hex: '#fbf3e0' },
  { group: 'Error', token: '--slds-g-color-error-base-10', hex: '#370114' },
  { group: 'Error', token: '--slds-g-color-error-base-15', hex: '#4b0620' },
  { group: 'Error', token: '--slds-g-color-error-base-20', hex: '#61022a' },
  { group: 'Error', token: '--slds-g-color-error-base-30', hex: '#8a033e' },
  { group: 'Error', token: '--slds-g-color-error-base-40', hex: '#b60554' },
  { group: 'Error', token: '--slds-g-color-error-base-50', hex: '#e3066a' },
  { group: 'Error', token: '--slds-g-color-error-base-60', hex: '#ff538a' },
  { group: 'Error', token: '--slds-g-color-error-base-65', hex: '#fe7298' },
  { group: 'Error', token: '--slds-g-color-error-base-70', hex: '#fe8aa7' },
  { group: 'Error', token: '--slds-g-color-error-base-80', hex: '#fdb6c5' },
  { group: 'Error', token: '--slds-g-color-error-base-90', hex: '#fddde3' },
  { group: 'Error', token: '--slds-g-color-error-base-95', hex: '#fef0f3' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-10', hex: '#181818' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-15', hex: '#242424' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-20', hex: '#2e2e2e' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-30', hex: '#444444' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-40', hex: '#5c5c5c' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-50', hex: '#757575' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-60', hex: '#939393' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-65', hex: '#a0a0a0' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-70', hex: '#aeaeae' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-80', hex: '#c9c9c9' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-90', hex: '#e5e5e5' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-95', hex: '#f3f3f3' },
  { group: 'Neutral', token: '--slds-g-color-neutral-base-100', hex: '#ffffff' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-10', hex: '#281202' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-15', hex: '#421604' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-20', hex: '#541d01' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-30', hex: '#7e2600' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-40', hex: '#aa3001' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-50', hex: '#d83a00' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-60', hex: '#ff5d2d' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-65', hex: '#ff784f' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-70', hex: '#ff906e' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-80', hex: '#feb9a5' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-90', hex: '#ffded5' },
  { group: 'Hot Orange', token: '--slds-g-color-palette-hot-orange-95', hex: '#fef1ed' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-10', hex: '#201600' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-15', hex: '#2e2204' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-20', hex: '#3e2b02' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-30', hex: '#5f3e02' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-40', hex: '#825101' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-50', hex: '#a96404' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-60', hex: '#dd7a01' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-65', hex: '#f38303' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-70', hex: '#fe9339' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-80', hex: '#ffba90' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-90', hex: '#fedfd0' },
  { group: 'Orange', token: '--slds-g-color-palette-orange-95', hex: '#fff1ea' },
  { group: 'Green', token: '--slds-g-color-palette-green-10', hex: '#071b12' },
  { group: 'Green', token: '--slds-g-color-palette-green-15', hex: '#0c2912' },
  { group: 'Green', token: '--slds-g-color-palette-green-20', hex: '#143b25' },
  { group: 'Green', token: '--slds-g-color-palette-green-30', hex: '#194e31' },
  { group: 'Green', token: '--slds-g-color-palette-green-40', hex: '#22683e' },
  { group: 'Green', token: '--slds-g-color-palette-green-50', hex: '#2e844a' },
  { group: 'Green', token: '--slds-g-color-palette-green-60', hex: '#3ba755' },
  { group: 'Green', token: '--slds-g-color-palette-green-65', hex: '#41b658' },
  { group: 'Green', token: '--slds-g-color-palette-green-70', hex: '#45c65a' },
  { group: 'Green', token: '--slds-g-color-palette-green-80', hex: '#91db8b' },
  { group: 'Green', token: '--slds-g-color-palette-green-90', hex: '#cdefc4' },
  { group: 'Green', token: '--slds-g-color-palette-green-95', hex: '#ebf7e6' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-10', hex: '#001a28' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-15', hex: '#0a2636' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-20', hex: '#023248' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-30', hex: '#084968' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-40', hex: '#05628a' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-50', hex: '#107cad' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-60', hex: '#0d9dda' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-65', hex: '#08abed' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-70', hex: '#1ab9ff' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-80', hex: '#90d0fe' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-90', hex: '#cfe9fe' },
  { group: 'Cloud Blue', token: '--slds-g-color-palette-cloud-blue-95', hex: '#eaf5fe' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-10', hex: '#17094e' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-15', hex: '#1f0974' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-20', hex: '#270c92' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-30', hex: '#2f2cb7' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-40', hex: '#3a49da' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-50', hex: '#5867e8' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-60', hex: '#7f8ced' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-65', hex: '#8e9bef' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-70', hex: '#9ea9f1' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-80', hex: '#bec7f6' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-90', hex: '#e0e5f8' },
  { group: 'Indigo', token: '--slds-g-color-palette-indigo-95', hex: '#f1f3fb' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-10', hex: '#240643' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-15', hex: '#300b60' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-20', hex: '#401075' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-30', hex: '#5a1ba9' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-40', hex: '#7526e3' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-50', hex: '#9050e9' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-60', hex: '#ad7bee' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-65', hex: '#b78def' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-70', hex: '#c29ef1' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-80', hex: '#d7bff2' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-90', hex: '#ece1f9' },
  { group: 'Purple', token: '--slds-g-color-palette-purple-95', hex: '#f6f2fb' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-10', hex: '#2e0039' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-15', hex: '#3d0157' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-20', hex: '#580276' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-30', hex: '#730394' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-40', hex: '#9602c7' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-50', hex: '#ba01ff' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-60', hex: '#cb65ff' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-65', hex: '#d17dfe' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-70', hex: '#d892fe' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-80', hex: '#e5b9fe' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-90', hex: '#f2defe' },
  { group: 'Violet', token: '--slds-g-color-palette-violet-95', hex: '#f9f0ff' },
  { group: 'Red', token: '--slds-g-color-palette-red-10', hex: '#300c01' },
  { group: 'Red', token: '--slds-g-color-palette-red-15', hex: '#4a0c04' },
  { group: 'Red', token: '--slds-g-color-palette-red-20', hex: '#640103' },
  { group: 'Red', token: '--slds-g-color-palette-red-30', hex: '#8e030f' },
  { group: 'Red', token: '--slds-g-color-palette-red-40', hex: '#ba0517' },
  { group: 'Red', token: '--slds-g-color-palette-red-50', hex: '#ea001e' },
  { group: 'Red', token: '--slds-g-color-palette-red-60', hex: '#fe5c4c' },
  { group: 'Red', token: '--slds-g-color-palette-red-65', hex: '#fe7765' },
  { group: 'Red', token: '--slds-g-color-palette-red-70', hex: '#fe8f7d' },
  { group: 'Red', token: '--slds-g-color-palette-red-80', hex: '#feb8ab' },
  { group: 'Red', token: '--slds-g-color-palette-red-90', hex: '#feded8' },
  { group: 'Red', token: '--slds-g-color-palette-red-95', hex: '#fef1ee' },
];

export function getColorByToken(token) {
  return sldsColors.find(c => c.token === token);
}
